"""add_token_version

Revision ID: 09f2093ec28e
Revises: 6b8c2e5f4a1d
Create Date: 2026-06-10 13:06:04.522192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f2093ec28e'
down_revision: Union[str, None] = '6b8c2e5f4a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('token_version', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'token_version')
    # ### end Alembic commands ###
