"""add_skill_grade_targets

Revision ID: 26520febf0b1
Revises: a1b2c3d4e5f6
Create Date: 2026-06-16 12:28:41.126646

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26520febf0b1"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skill_grade_targets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("grade", sa.String(length=20), nullable=False),
        sa.Column("expected_level", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(
        "ix_assessment_history_assessment_id", table_name="assessment_history"
    )
    op.drop_index("ix_assessments_employee_id", table_name="assessments")
    op.drop_index("ix_assessments_skill_id", table_name="assessments")
    op.drop_index("ix_employee_profiles_employee_id", table_name="employee_profiles")
    op.drop_index("ix_ipr_plans_employee_id", table_name="ipr_plans")
    op.drop_index(
        "ix_review_assessments_review_cycle_id", table_name="review_assessments"
    )
    op.drop_constraint("uq_review_cycle_skill", "review_assessments", type_="unique")
    op.drop_index("ix_review_cycles_employee_id", table_name="review_cycles")
    op.drop_index("ix_review_cycles_status", table_name="review_cycles")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_review_cycles_status", "review_cycles", ["status"], unique=False
    )
    op.create_index(
        "ix_review_cycles_employee_id", "review_cycles", ["employee_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_review_cycle_skill", "review_assessments", ["review_cycle_id", "skill_id"]
    )
    op.create_index(
        "ix_review_assessments_review_cycle_id",
        "review_assessments",
        ["review_cycle_id"],
        unique=False,
    )
    op.create_index(
        "ix_ipr_plans_employee_id", "ipr_plans", ["employee_id"], unique=False
    )
    op.create_index(
        "ix_employee_profiles_employee_id",
        "employee_profiles",
        ["employee_id"],
        unique=True,
    )
    op.create_index(
        "ix_assessments_skill_id", "assessments", ["skill_id"], unique=False
    )
    op.create_index(
        "ix_assessments_employee_id", "assessments", ["employee_id"], unique=False
    )
    op.create_index(
        "ix_assessment_history_assessment_id",
        "assessment_history",
        ["assessment_id"],
        unique=False,
    )
    op.drop_table("skill_grade_targets")
    # ### end Alembic commands ###
